### ISSUE TITLE
`requirements.py` gera `MissingPackageError` durante verificação de dependências opcionais `package[deps]`

### ISSUE THREAD

**Issue by hslinhares** [splor-mg/cookiecutter-datapackage#24]
```Checking python packages...
2023-12-07T15:03:02-0300 WARNI [__main__] Required packages are missing: frictionless[html]
Traceback (most recent call last):
  File "C:\Users\Henrique\assessoria_dados\classificadores-sisor\scripts\requirements.py", line 72, in <module>
    check_requirements()
  File "C:\Users\Henrique\assessoria_dados\classificadores-sisor\scripts\requirements.py", line 31, in check_requirements
    raise exceptions.MissingPackageError
exceptions.MissingPackageError
make: *** [Makefile:15: requirements] Error 1```

**Comment by labanca** [comment]
Observei algo que pode ser relevante nesse caso. Ao instalar o pacote `frictionless[html]` parece que a instalação procede em instalar o pacote frictionless básico e outros pacotes relativos a essa "versão" frictionless[html]. Ao rodar o `pip install frictionless[html]` o seguinte output aparece no console:

```
 pip install frictionless[html]
Requirement already satisfied: frictionless[html] in c:\projects\requirements_fix\venv\lib\site-packages (5.16.1)
Requirement already satisfied: attrs>=22.2.0 in c:\projects\requirements_fix\venv\lib\site-packages (from frictionless[html]) (23.2.0)
Requirement already satisfied: chardet>=3.0 in c:\projects\requirements_fix\venv\lib\site-packages (from frictionless[html]) (5.2.0)
Requirement already satisfied: humanize>=4.2 in c:\projects\requirements_fix\venv\lib\site-packages (from frictionless[html]) (4.9.0)
Requirement already satisfied: isodate>=0.6 in c:\projects\requirements_fix\venv\lib\site-packages (from frictionless[html]) (0.6.1)
Requirement already satisfied: jinja2>=3.0 in c:\projects\requirements_fix\venv\lib\site-packages (from frictionless[html]) (3.1.3)
Requirement already satisfied: jsonschema<4.18 in c:\projects\requirements_fix\venv\lib\site-packages (from frictionless[html]) (4.17.3)
Requirement already satisfied: marko>=1.0 in c:\projects\requirements_fix\venv\lib\site-packages (from frictionless[html]) (2.0.3)
Requirement already satisfied: petl>=1.6 in c:\projects\requirements_fix\venv\lib\site-packages (from frictionless[html]) (1.7.15)
Requirement already satisfied: pydantic>=2.0 in c:\projects\requirements_fix\venv\lib\site-packages (from frictionless[html]) (2.7.0)
Requirement already satisfied: python-dateutil>=2.8 in c:\projects\requirements_fix\venv\lib\site-packages (from frictionless[html]) (2.9.0.post0)
Requirement already satisfied: python-slugify>=1.2 in c:\projects\requirements_fix\venv\lib\site-packages (from frictionless[html]) (8.0.4)
Requirement already satisfied: pyyaml>=5.3 in c:\projects\requirements_fix\venv\lib\site-packages (from frictionless[html]) (6.0.1)
Requirement already satisfied: requests>=2.10 in c:\projects\requirements_fix\venv\lib\site-packages (from frictionless[html]) (2.31.0)
Requirement already satisfied: rfc3986>=1.4 in c:\projects\requirements_fix\venv\lib\site-packages (from frictionless[html]) (2.0.0)
Requirement already satisfied: simpleeval>=0.9.11 in c:\projects\requirements_fix\venv\lib\site-packages (from frictionless[html]) (0.9.13)
Requirement already satisfied: stringcase>=1.2 in c:\projects\requirements_fix\venv\lib\site-packages (from frictionless[html]) (1.2.0)
Requirement already satisfied: tabulate>=0.8.10 in c:\projects\requirements_fix\venv\lib\site-packages (from frictionless[html]) (0.9.0)
Requirement already satisfied: typer>=0.5 in c:\projects\requirements_fix\venv\lib\site-packages (from typer[all]>=0.5->frictionless[html]) (0.12.3)
Requirement already satisfied: typing-extensions>=4.3 in c:\projects\requirements_fix\venv\lib\site-packages (from frictionless[html]) (4.11.0)
Requirement already satisfied: validators>=0.18 in c:\projects\requirements_fix\venv\lib\site-packages (from frictionless[html]) (0.28.0)
Requirement already satisfied: pyquery>=1.4 in c:\projects\requirements_fix\venv\lib\site-packages (from frictionless[html]) (2.0.0)
Requirement already satisfied: six in c:\projects\requirements_fix\venv\lib\site-packages (from isodate>=0.6->frictionless[html]) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\projects\requirements_fix\venv\lib\site-packages (from jinja2>=3.0->frictionless[html]) (2.1.5)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\projects\requirements_fix\venv\lib\site-packages (from jsonschema<4.18->frictionless[html]) (0.20.0)
Requirement already satisfied: annotated-types>=0.4.0 in c:\projects\requirements_fix\venv\lib\site-packages (from pydantic>=2.0->frictionless[html]) (0.6.0)
Requirement already satisfied: pydantic-core==2.18.1 in c:\projects\requirements_fix\venv\lib\site-packages (from pydantic>=2.0->frictionless[html]) (2.18.1)
Requirement already satisfied: lxml>=2.1 in c:\projects\requirements_fix\venv\lib\site-packages (from pyquery>=1.4->frictionless[html]) (5.2.1)
Requirement already satisfied: cssselect>=1.2.0 in c:\projects\requirements_fix\venv\lib\site-packages (from pyquery>=1.4->frictionless[html]) (1.2.0)
Requirement already satisfied: text-unidecode>=1.3 in c:\projects\requirements_fix\venv\lib\site-packages (from python-slugify>=1.2->frictionless[html]) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\projects\requirements_fix\venv\lib\site-packages (from requests>=2.10->frictionless[html]) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\projects\requirements_fix\venv\lib\site-packages (from requests>=2.10->frictionless[html]) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\projects\requirements_fix\venv\lib\site-packages (from requests>=2.10->frictionless[html]) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\projects\requirements_fix\venv\lib\site-packages (from requests>=2.10->frictionless[html]) (2024.2.2)
Requirement already satisfied: click>=8.0.0 in c:\projects\requirements_fix\venv\lib\site-packages (from typer>=0.5->typer[all]>=0.5->frictionless[html]) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in c:\projects\requirements_fix\venv\lib\site-packages (from typer>=0.5->typer[all]>=0.5->frictionless[html]) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\projects\requirements_fix\venv\lib\site-packages (from typer>=0.5->typer[all]>=0.5->frictionless[html]) (13.7.1)
WARNING: typer 0.12.3 does not provide the extra 'all'
Requirement already satisfied: colorama in c:\projects\requirements_fix\venv\lib\site-packages (from click>=8.0.0->typer>=0.5->typer[all]>=0.5->frictionless[html]) (0.4.6)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\projects\requirements_fix\venv\lib\site-packages (from rich>=10.11.0->typer>=0.5->typer[all]>=0.5->frictionless[html]) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\projects\requirements_fix\venv\lib\site-packages (from rich>=10.11.0->typer>=0.5->typer[all]>=0.5->frictionless[html]) (2.17.2)
Requirement already satisfied: mdurl~=0.1 in c:\projects\requirements_fix\venv\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer>=0.5->typer[all]>=0.5->frictionless[html]) (0.1.2)
```

Estou investigando a melhor forma de lidar com essa situação e se todos os pacotes com dependências, na forma package[dep], funcionam dessa mesma maneira.

**Comment by labanca** [comment]
Os pacotes na forma `package[extras]` instalam dependências adicionais, mas não são, [até onde encontrei informação](https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/#Extras), pacotes diferentes em si. Dessa forma, instalar  `frictionless[html]` instala o pacote frictionless padrão e depedências adicionais indicadas pelo extra `[html]`. 

De acordo com a [documentação](https://packaging.python.org/en/latest/tutorials/installing-packages/#installing-extras) do Python:

>Extras are optional “variants” of a package, which may include additional dependencies, and thereby enable additional functionality from the package.

Com esse contexto, remover os `[extras]` das strings dos pacotes, mas mantendo os números das versões, resolveria o problema. 

Além disso, observando o código, percebi que o arquivo de entrada dos pacotes usado pelo `requirements.py` atualmente é o arquivo `requirements.in`, sendo que parece fazer mais sentido que seja o `requirements.txt`, que contém os pacotes do requirements.in e as demais dependências geradas pelo `pip-compile`. @fjuniorr se puder validar esse entendimento.
